### ISSUE TITLE
UUIDをパース

### ISSUE THREAD

**Issue by H1rono** [H1rono/traq-bot-http-rs#17]
**機能追加の動機**
使用者側にパースさせるのは望ましくない

**望ましい解決方法**
`Cargo.toml`に次のように書くことで[uuid](https://docs.rs/uuid/latest/uuid/)の型に書き換える

```toml
[dependencies]
traq-bot-http = { version = "...", features = ["uuid", "..."] }
```

**他に検討した代替案**

**補足説明**
